# Generated by Django 4.2 on 2023-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='book',
        ),
        migrations.AddField(
            model_name='basket',
            name='book',
            field=models.ManyToManyField(to='library.book'),
        ),
    ]
